name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.x"
          channel: "stable"
      - name: Tests
        run: flutter test

      - name: Create APK
        run: flutter pub get && flutter build apk --release --flavor demo

      - uses: actions/upload-artifact@v4
        with:
          name: Upload APK
          path: build/app/outputs/flutter-apk/app-demo-release.apk
